# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

# Virtual Machine 1 Settings
  config.vm.define "Ubuntu-bionic64-vm" do |vm1|
    vm1.vm.hostname = "Ubuntu-bionic64-vm"
    vm1.vm.box = "ubuntu/bionic64"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

#   Provider Settings
    vm1.vm.provider "virtualbox" do |vb|
       vb.name = "Ubuntu-bionic64-vm"
       vb.gui = false
       vb.memory = "1024"
    end

#   Provision Settings
    vm1.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
   SHELL

   vm1.vm.provision "shell", run: "always", inline: <<-SHELL
     echo "Hello from Ubuntu VM machine"
   SHELL
  end

# Virtual Machine 2  Settings
  config.vm.define "Centos-7-vm" do |vm2|
    vm2.vm.hostname = "Centos-7-vm"
    vm2.vm.box = "centos/7"

  vm2.vm.provider "virtualbox" do |vb|
     vb.name = "Centos-7-vm"
     vb.gui = false
     vb.memory = "1024"
  end

   vm2.vm.provision "shell", run: "always", inline: <<-SHELL
     echo "Hello from Centos VM machine"
   SHELL
  end
end
